### PR TITLE
Milestone 1: Initialized Hello World Project

### PR DESCRIPTION
**Pull request by prg-04**
## In this repository, I have done the following to set up the Hello_World Project:

- [ ] Add a Descriptive ReadMe file.
- [ ] Add all necessary Dependencies
- [ ] Removed all linters error

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @prg-04 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR

## Required Changes ♻️
_Check the comments under the review._

- [ ] In the `.gitignore` file there should be a listing of the `test.md` file along with `node_modules` folder. Kindly add the `test.md` file to the `.gitignore` file.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @prg-04, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Congrats

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Requested  change has been implemented


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prg-04** [comment]
Hello @emmiiorji  I can see you've Indicated "Changes required but i can't see the suggested changes...I have already implemented the suggested changes by the last reviewer

**Comment by emmiiorji** [comment]
Hi @prg-04

Sorry, that was an error while leaving comment. I'm sure your project is approved on the dashboard. Kindly indicate if otherwise.

**Pull request merged**
